services:
  # Nodo principal (3001)
  dpos-node-main:
    build: .
    container_name: dpos-node-main
    ports:
      - "3001:3001"
    environment:
      - NODE_ID=main
      - PORT=3001
      - NETWORK=local
    networks:
      - dpos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/dpos-node", "--health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Delegados (3002-3023)
  dpos-delegate-1:
    build: .
    container_name: dpos-delegate-1
    ports:
      - "3002:3001"
    environment:
      - NODE_ID=delegate-1
      - PORT=3001
      - EXTERNAL_PORT=3002
      - NETWORK=local
      - IS_DELEGATE=true
    networks:
      - dpos-network
    restart: unless-stopped
    depends_on:
      - dpos-node-main

  dpos-delegate-2:
    build: .
    container_name: dpos-delegate-2
    ports:
      - "3003:3001"
    environment:
      - NODE_ID=delegate-2
      - PORT=3001
      - EXTERNAL_PORT=3003
      - NETWORK=local
      - IS_DELEGATE=true
    networks:
      - dpos-network
    restart: unless-stopped
    depends_on:
      - dpos-node-main

  dpos-delegate-3:
    build: .
    container_name: dpos-delegate-3
    ports:
      - "3004:3001"
    environment:
      - NODE_ID=delegate-3
      - PORT=3001
      - EXTERNAL_PORT=3004
      - NETWORK=local
      - IS_DELEGATE=true
    networks:
      - dpos-network
    restart: unless-stopped
    depends_on:
      - dpos-node-main

  dpos-delegate-4:
    build: .
    container_name: dpos-delegate-4
    ports:
      - "3005:3001"
    environment:
      - NODE_ID=delegate-4
      - PORT=3001
      - EXTERNAL_PORT=3005
      - NETWORK=local
      - IS_DELEGATE=true
    networks:
      - dpos-network
    restart: unless-stopped
    depends_on:
      - dpos-node-main

  dpos-delegate-5:
    build: .
    container_name: dpos-delegate-5
    ports:
      - "3006:3001"
    environment:
      - NODE_ID=delegate-5
      - PORT=3001
      - EXTERNAL_PORT=3006
      - NETWORK=local
      - IS_DELEGATE=true
    networks:
      - dpos-network
    restart: unless-stopped
    depends_on:
      - dpos-node-main

  dpos-delegate-6:
    build: .
    container_name: dpos-delegate-6
    ports:
      - "3007:3001"
    environment:
      - NODE_ID=delegate-6
      - PORT=3001
      - EXTERNAL_PORT=3007
      - NETWORK=local
      - IS_DELEGATE=true
    networks:
      - dpos-network
    restart: unless-stopped
    depends_on:
      - dpos-node-main

  dpos-delegate-7:
    build: .
    container_name: dpos-delegate-7
    ports:
      - "3008:3001"
    environment:
      - NODE_ID=delegate-7
      - PORT=3001
      - EXTERNAL_PORT=3008
      - NETWORK=local
      - IS_DELEGATE=true
    networks:
      - dpos-network
    restart: unless-stopped
    depends_on:
      - dpos-node-main

  dpos-delegate-8:
    build: .
    container_name: dpos-delegate-8
    ports:
      - "3009:3001"
    environment:
      - NODE_ID=delegate-8
      - PORT=3001
      - EXTERNAL_PORT=3009
      - NETWORK=local
      - IS_DELEGATE=true
    networks:
      - dpos-network
    restart: unless-stopped
    depends_on:
      - dpos-node-main

  dpos-delegate-9:
    build: .
    container_name: dpos-delegate-9
    ports:
      - "3010:3001"
    environment:
      - NODE_ID=delegate-9
      - PORT=3001
      - EXTERNAL_PORT=3010
      - NETWORK=local
      - IS_DELEGATE=true
    networks:
      - dpos-network
    restart: unless-stopped
    depends_on:
      - dpos-node-main

  dpos-delegate-10:
    build: .
    container_name: dpos-delegate-10
    ports:
      - "3011:3001"
    environment:
      - NODE_ID=delegate-10
      - PORT=3001
      - EXTERNAL_PORT=3011
      - NETWORK=local
      - IS_DELEGATE=true
    networks:
      - dpos-network
    restart: unless-stopped
    depends_on:
      - dpos-node-main

  dpos-delegate-11:
    build: .
    container_name: dpos-delegate-11
    ports:
      - "3012:3001"
    environment:
      - NODE_ID=delegate-11
      - PORT=3001
      - EXTERNAL_PORT=3012
      - NETWORK=local
      - IS_DELEGATE=true
    networks:
      - dpos-network
    restart: unless-stopped
    depends_on:
      - dpos-node-main

  dpos-delegate-12:
    build: .
    container_name: dpos-delegate-12
    ports:
      - "3013:3001"
    environment:
      - NODE_ID=delegate-12
      - PORT=3001
      - EXTERNAL_PORT=3013
      - NETWORK=local
      - IS_DELEGATE=true
    networks:
      - dpos-network
    restart: unless-stopped
    depends_on:
      - dpos-node-main

  dpos-delegate-13:
    build: .
    container_name: dpos-delegate-13
    ports:
      - "3014:3001"
    environment:
      - NODE_ID=delegate-13
      - PORT=3001
      - EXTERNAL_PORT=3014
      - NETWORK=local
      - IS_DELEGATE=true
    networks:
      - dpos-network
    restart: unless-stopped
    depends_on:
      - dpos-node-main

  dpos-delegate-14:
    build: .
    container_name: dpos-delegate-14
    ports:
      - "3015:3001"
    environment:
      - NODE_ID=delegate-14
      - PORT=3001
      - EXTERNAL_PORT=3015
      - NETWORK=local
      - IS_DELEGATE=true
    networks:
      - dpos-network
    restart: unless-stopped
    depends_on:
      - dpos-node-main

  dpos-delegate-15:
    build: .
    container_name: dpos-delegate-15
    ports:
      - "3016:3001"
    environment:
      - NODE_ID=delegate-15
      - PORT=3001
      - EXTERNAL_PORT=3016
      - NETWORK=local
      - IS_DELEGATE=true
    networks:
      - dpos-network
    restart: unless-stopped
    depends_on:
      - dpos-node-main

  dpos-delegate-16:
    build: .
    container_name: dpos-delegate-16
    ports:
      - "3017:3001"
    environment:
      - NODE_ID=delegate-16
      - PORT=3001
      - EXTERNAL_PORT=3017
      - NETWORK=local
      - IS_DELEGATE=true
    networks:
      - dpos-network
    restart: unless-stopped
    depends_on:
      - dpos-node-main

  dpos-delegate-17:
    build: .
    container_name: dpos-delegate-17
    ports:
      - "3018:3001"
    environment:
      - NODE_ID=delegate-17
      - PORT=3001
      - EXTERNAL_PORT=3018
      - NETWORK=local
      - IS_DELEGATE=true
    networks:
      - dpos-network
    restart: unless-stopped
    depends_on:
      - dpos-node-main

  dpos-delegate-18:
    build: .
    container_name: dpos-delegate-18
    ports:
      - "3019:3001"
    environment:
      - NODE_ID=delegate-18
      - PORT=3001
      - EXTERNAL_PORT=3019
      - NETWORK=local
      - IS_DELEGATE=true
    networks:
      - dpos-network
    restart: unless-stopped
    depends_on:
      - dpos-node-main

  dpos-delegate-19:
    build: .
    container_name: dpos-delegate-19
    ports:
      - "3020:3001"
    environment:
      - NODE_ID=delegate-19
      - PORT=3001
      - EXTERNAL_PORT=3020
      - NETWORK=local
      - IS_DELEGATE=true
    networks:
      - dpos-network
    restart: unless-stopped
    depends_on:
      - dpos-node-main

  dpos-delegate-20:
    build: .
    container_name: dpos-delegate-20
    ports:
      - "3021:3001"
    environment:
      - NODE_ID=delegate-20
      - PORT=3001
      - EXTERNAL_PORT=3021
      - NETWORK=local
      - IS_DELEGATE=true
    networks:
      - dpos-network
    restart: unless-stopped
    depends_on:
      - dpos-node-main

  dpos-delegate-21:
    build: .
    container_name: dpos-delegate-21
    ports:
      - "3022:3001"
    environment:
      - NODE_ID=delegate-21
      - PORT=3001
      - EXTERNAL_PORT=3022
      - NETWORK=local
      - IS_DELEGATE=true
    networks:
      - dpos-network
    restart: unless-stopped
    depends_on:
      - dpos-node-main

  dpos-delegate-22:
    build: .
    container_name: dpos-delegate-22
    ports:
      - "3023:3001"
    environment:
      - NODE_ID=delegate-22
      - PORT=3001
      - EXTERNAL_PORT=3023
      - NETWORK=local
      - IS_DELEGATE=true
    networks:
      - dpos-network
    restart: unless-stopped
    depends_on:
      - dpos-node-main

networks:
  dpos-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16