apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpos-delegates
  namespace: dpos-network
  labels:
    app: dpos-delegates
    component: delegate
spec:
  replicas: 22
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 3
  selector:
    matchLabels:
      app: dpos-delegates
  template:
    metadata:
      labels:
        app: dpos-delegates
        component: delegate
    spec:
      serviceAccountName: dpos-sa
      containers:
        - name: dpos-node
          image: dpos-node:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
              name: http
              protocol: TCP
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PORT
              value: "3001"
            - name: NETWORK
              valueFrom:
                configMapKeyRef:
                  name: dpos-config
                  key: network
            - name: IS_DELEGATE
              value: "true"
            - name: MAIN_NODE_URL
              value: "http://dpos-main-service:3001"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5
