apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-config
  namespace: dpos-network
  labels:
    app: validator-node
    component: mcp
data:
  config.json: |
    {
      "mcpServiceEnabled": true,
      "defaultQueryTimeoutSeconds": 30,
      "maxConcurrentQueriesPerNode": 10,
      "logLevel": "INFO",
      "llmService": {
        "enabled": true,
        "provider": "openai",
        "model": "gpt-3.5-turbo",
        "maxTokens": 1000,
        "temperature": 0.7,
        "minResponsesForAggregation": 1,
        "responseAggregationStrategy": "firstValid",
        "timeoutSeconds": 30
      },
      "nodeBlacklist": [],
      "healthCheck": {
        "enabled": true,
        "intervalSeconds": 60
      },
      "metrics": {
        "enabled": true,
        "port": 9091
      }
    }
