apiVersion: v1
kind: PersistentVolume
metadata:
  name: validator-node-pv
  labels:
    app: validator-node
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data/validator-node
